### ISSUE TITLE
Why the apk file size of such a simple game with a few materials is almoust 10 MB?

### ISSUE THREAD

**Issue by mrmrn** [KOBUGE-Games/Ninja-Training#5]
Hi,
I have a question about the size of ninja traning on android devices? and how to keep it size much lower than now?

**Comment by akien-mga** [comment]
As all Godot games, Ninja Training's apk contains not only the assets but also the whole game engine runtime, which is about 6 MB with default settings. It might be possible to bring it down somewhat by compiling Godot's android export template without support for e.g. 3D features or some drivers that are not in use in Ninja Training, but it probably won't remove more than 1 MB to the runtime.

**Comment by est31** [comment]
An overview over the size of the apk in the f-droid store:
- The main godot engine file `libgodot_android.so` (6.1 mb compressed, 17 mb uncompressed)
- The music file `blackmoor_ninjas.ogg` (2.6 mb compressed and uncompressed)
- lots of useless play store button res files (1.2 mb uncompressed). They got added by godot, and got removed in the 2.0 version of godot, which ninjatraining doesn't use yet however. The usual suspect is removed by the f-droid build process, but those were missed...

The .so file got larger by 2 mb since 1.1, so dunno if switching to 2.0 would really decrease size, it would have to be tested.

I'll make a new release that should remove the google proprietary files.

**Comment by mrmrn** [comment]
thank you both

**Comment by bojidar-bg** [comment]
@akien-mga @mrmrn Close?

**Comment by est31** [comment]
I think so

**Comment by mrmrn** [comment]
@bojidar-bg 
yeah, I just wanted to know why the apk export is so large in size and the answers was very good.
thank you all
